# Generated by Django 3.1.3 on 2020-11-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('date', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
